### ISSUE TITLE
Instant crash when adding domain

### ISSUE THREAD

**Issue by GottfriedHofmann** [sebbas/blender-mantaflow#1]
Hello Sebbas,

I just compiled this repo on Ubuntu 15.10 x64 and tried to add a domain to the default cube which resulted in a reproducible instant crash. Here is the blender.crash.txt (I first tried collision and flow, both worked, but the instant I select "domain" it crashes):
# Blender 2.76 (sub 9), Commit date: 2016-04-23 11:48, Hash a59e9cd

bpy.context.space_data.context = 'PHYSICS'  # Property
bpy.ops.object.modifier_add(type='SMOKE')  # Operator
bpy.context.object.modifiers["Smoke"].smoke_type = 'COLLISION'  # Property
bpy.context.object.modifiers["Smoke"].smoke_type = 'FLOW'  # Property
# backtrace

./blender(BLI_system_backtrace+0x30) [0x1461a10]
./blender() [0x988741]
/lib/x86_64-linux-gnu/libc.so.6(+0x352f0) [0x7f6dde4392f0]
/usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0(PyObject_GetAttrString+0) [0x7f6de1bc6d70]
./blender(_ZN5MANTA14getGridPointerENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_+0x73) [0x98c723]
./blender(_ZN5MANTA14updatePointersEP17SmokeModifierData+0x295) [0x98cdf5]
./blender(_ZN5MANTAC1EPiP17SmokeModifierData+0x418) [0x991128]
./blender(smoke_init+0x25) [0x98ab25]
./blender(smoke_reallocate_fluid+0x5c) [0x12482dc]
./blender() [0x124c031]
./blender(smokeModifier_do+0x2e5) [0x124c895]
./blender() [0x1107257]
./blender() [0x1107f50]
./blender(makeDerivedMesh+0x8d) [0x110806d]
./blender(BKE_object_handle_data_update+0x495) [0x11f3e35]
./blender(BKE_object_handle_update_ex+0x200) [0x11ee320]
./blender() [0x1229f26]
./blender() [0x1461ccc]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76aa) [0x7f6ddfff66aa]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f6dde50ae9d]

**Comment by sebbas** [comment]
Hi Gottfried,

sorry about that - I had some changes that I left out in the last commit. It was only working for me locally. Paired with a bit of overconfidence that it would work remotely as well, you got the crash :~)

I pushed the changes and the latest commit (Hash 39f65a9) works for me on Ubuntu 14.04 LTS

Hope this fixes the issue!

**Comment by GottfriedHofmann** [comment]
Compilation and running is all fine now - thanks a lot - you can close this issue for good :)
