### ISSUE TITLE
OpenImageIO and Pugi on Debian Sid

### ISSUE THREAD

**Issue by reanimastudios** [sebbas/blender-mantaflow#16]
In file included from /home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp:17:0:
/home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/../graph/node_xml.h:31:51: error: reference to ‘pugi’ is ambiguous
 void xml_read_node(XMLReader& reader, Node *node, pugi::xml_node xml_node);
                                                   ^~~~
In file included from /home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/../util/util_xml.h:22:0,
                 from /home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/../graph/node_xml.h:23,
                 from /home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp:17:
/usr/include/OpenImageIO/pugixml.hpp:109:28: note: candidates are: namespace pugi = OpenImageIO_v1_8::OpenImageIO_v1_8::pugi;
 namespace pugi = OIIO::pugi;
                            ^
/usr/include/OpenImageIO/pugixml.hpp:107:11: note:                 namespace OpenImageIO_v1_8::pugi { }
 namespace pugi {}
           ^~~~
In file included from /home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp:17:0:
/home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/../graph/node_xml.h:31:66: error: expected ‘,’ or ‘...’ before ‘xml_node’
 void xml_read_node(XMLReader& reader, Node *node, pugi::xml_node xml_node);
                                                                  ^~~~~~~~
/home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/../graph/node_xml.h:32:1: error: reference to ‘pugi’ is ambiguous
 pugi::xml_node xml_write_node(Node *node, pugi::xml_node xml_root);
 ^~~~
In file included from /home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/../util/util_xml.h:22:0,
                 from /home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/../graph/node_xml.h:23,
                 from /home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp:17:
/usr/include/OpenImageIO/pugixml.hpp:109:28: note: candidates are: namespace pugi = OpenImageIO_v1_8::OpenImageIO_v1_8::pugi;
 namespace pugi = OIIO::pugi;
                            ^
/usr/include/OpenImageIO/pugixml.hpp:107:11: note:                 namespace OpenImageIO_v1_8::pugi { }
 namespace pugi {}
           ^~~~
/home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/extern/curve_fit_nd/intern/curve_fit_cubic_refit.c: In function ‘curve_fit_cubic_to_points_refit_db’:
/home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/extern/curve_fit_nd/intern/curve_fit_cubic_refit.c:1281:47: warning: ‘len_next’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    knots[knots_len - 1].handles[1] = len_next / -3;
                                      ~~~~~~~~~^~~~
/home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp:36:44: error: reference to ‘pugi’ is ambiguous
 static void xml_read_float_array(T& value, pugi::xml_attribute attr)
                                            ^~~~
In file included from /home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/../util/util_xml.h:22:0,
                 from /home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/../graph/node_xml.h:23,
                 from /home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp:17:
/usr/include/OpenImageIO/pugixml.hpp:109:28: note: candidates are: namespace pugi = OpenImageIO_v1_8::OpenImageIO_v1_8::pugi;
 namespace pugi = OIIO::pugi;
                            ^
/usr/include/OpenImageIO/pugixml.hpp:107:11: note:                 namespace OpenImageIO_v1_8::pugi { }
 namespace pugi {}
           ^~~~
/home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp:36:64: error: expected ‘,’ or ‘...’ before ‘attr’
 static void xml_read_float_array(T& value, pugi::xml_attribute attr)
                                                                ^~~~
/home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp: In function ‘void ccl::xml_read_float_array(T&, int)’:
/home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp:39:23: error: ‘attr’ was not declared in this scope
  string_split(tokens, attr.value());
                       ^~~~
/home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp:39:23: note: suggested alternative: ‘atol’
  string_split(tokens, attr.value());
                       ^~~~
                       atol
/home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp: At global scope:
/home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp:54:51: error: reference to ‘pugi’ is ambiguous
 void xml_read_node(XMLReader& reader, Node *node, pugi::xml_node xml_node)
                                                   ^~~~
In file included from /home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/../util/util_xml.h:22:0,
                 from /home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/../graph/node_xml.h:23,
                 from /home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp:17:
/usr/include/OpenImageIO/pugixml.hpp:109:28: note: candidates are: namespace pugi = OpenImageIO_v1_8::OpenImageIO_v1_8::pugi;
 namespace pugi = OIIO::pugi;
                            ^
/usr/include/OpenImageIO/pugixml.hpp:107:11: note:                 namespace OpenImageIO_v1_8::pugi { }
 namespace pugi {}
           ^~~~
/home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp:54:66: error: expected ‘,’ or ‘...’ before ‘xml_node’
 void xml_read_node(XMLReader& reader, Node *node, pugi::xml_node xml_node)
                                                                  ^~~~~~~~
/home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp: In function ‘void ccl::xml_read_node(ccl::XMLReader&, ccl::Node*, int)’:
/home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp:56:2: error: reference to ‘pugi’ is ambiguous
  pugi::xml_attribute name_attr = xml_node.attribute("name");
  ^~~~
In file included from /home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/../util/util_xml.h:22:0,
                 from /home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/../graph/node_xml.h:23,
                 from /home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp:17:
/usr/include/OpenImageIO/pugixml.hpp:109:28: note: candidates are: namespace pugi = OpenImageIO_v1_8::OpenImageIO_v1_8::pugi;
 namespace pugi = OIIO::pugi;
                            ^
/usr/include/OpenImageIO/pugixml.hpp:107:11: note:                 namespace OpenImageIO_v1_8::pugi { }
 namespace pugi {}
           ^~~~
/home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp:57:5: error: ‘name_attr’ was not declared in this scope
  if(name_attr) {
     ^~~~~~~~~
/home/mdriftmeyer/Blender/Blender-2.79-Release/BlenderMantaflow-2.79/intern/cycles/graph/node_xml.cpp:69:3: error: reference to ‘pugi’ is ambiguous
   pugi::xml_attribute attr = xml_node.attribute(socket.name.c_str());
   ^~~~
----------------------------

Useless until this is resolved.

**Comment by sebbas** [comment]
Hi!

Interesting log - is it really because of Manta, i.e. does it only happen in the "fluid-mantaflow" branch? At least from the error messages it looks like something else.

So, if you have more info on when this happens and with which build, that would be great!

**Comment by reanimastudios** [comment]
I'll have to rebuild Manta branch to see if the newer release of OpenImageIO has fixed this.

**Comment by reanimastudios** [comment]
Checkout from master, rebuilt against OpoenImageIO in Debian cleanly. You can close this issue.

**Comment by sebbas** [comment]
Okay thanks, good to know!
