### ISSUE TITLE
Building this commit causes an error

### ISSUE THREAD

**Issue by Esimacio** [sebbas/blender-mantaflow#18]
Can't build on any machine (with windows 10)

Error: " C:\blender-git\blender\source\blender\makesrna\intern\rna_smo ke.c(750): error C4133: 'function' : incompatible types - from 'WTURBULENCE *' to 'FLUID *' (C:\blender-git\build_windows_Release_x64_vc12_Release\source\ blender\makesrna\intern\rna_smoke_gen.c) [C:\blender-git\build_windows_Release_x64_vc12_Release\source\ blender\
makesrna\intern\bf_rna.vcxproj]"

**Comment by sebbas** [comment]
Hi! Yes, I see what you mean. Fix for this issue just wasn't pushed yet.

Can you retry with 908dbedff32896daf7cc99c99a570ffd9a214300?

**Comment by sebbas** [comment]
908dbedff32896daf7cc99c99a570ffd9a214300 fixed the issue
