### ISSUE TITLE
lose the emitter shape when increase subframes

### ISSUE THREAD

**Issue by ghost** [sebbas/blender-mantaflow#2]
If you increase the subframes in the liquid fluid flow, you lose the shape of the emitter, and start emitting as a square emitter. With a value of 0 this does not happen.

**Comment by sebbas** [comment]
Hey! Thanks for pointing this out and sorry, totally forgot about this report. But hey, better fix it late than never :)

I think I found the problem: When combining the emission maps, the values for the "inflow_maps" (the equivalent of Mantas phi grid in Blender) were not copied to the temporary emission map which is used for subframes.

@zebus3d Can you try out the latest commit (Hash 5cd5f9e). I think it fixes the issue.

**Comment by ghost** [comment]
@sebbas Do not worry about delay, Take your time. Thanks for answering!!, And thanks for solving it so fast!! :D I'm going to try the version Hash 5cd5f9e.
