### ISSUE TITLE
Compile Error Ubuntu 17.10 x64

### ISSUE THREAD

**Issue by GottfriedHofmann** [sebbas/blender-mantaflow#22]
> [ 19%] Building CXX object intern/mantaflow/CMakeFiles/bf_intern_mantaflow.dir/intern/manta_fluid_API.cpp.o
/home/g/blender-git/blender/intern/mantaflow/intern/manta_fluid_API.cpp: In function ‘int fluid_bake_geometry(FLUID*, SmokeModifierData*, int)’:
/home/g/blender-git/blender/intern/mantaflow/intern/manta_fluid_API.cpp:888:1: error: no return statement in function returning non-void [-Werror=return-type]
 }
 ^
cc1plus: some warnings being treated as errors
intern/mantaflow/CMakeFiles/bf_intern_mantaflow.dir/build.make:86: recipe for target 'intern/mantaflow/CMakeFiles/bf_intern_mantaflow.dir/intern/manta_fluid_API.cpp.o' failed
make[2]: *** [intern/mantaflow/CMakeFiles/bf_intern_mantaflow.dir/intern/manta_fluid_API.cpp.o] Error 1
CMakeFiles/Makefile2:1373: recipe for target 'intern/mantaflow/CMakeFiles/bf_intern_mantaflow.dir/all' failed
make[1]: *** [intern/mantaflow/CMakeFiles/bf_intern_mantaflow.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sebbas** [comment]
Oh, sorry about that. That was just a missing return statement in one of the functions. It slipped into the commit as it was just a warning on my machine and compiled without errors. Should be fixed in latest commit :)

Edit: should be fixed in 86c49311a45fa1fb8ebea122ce2f8cc569c6079a
