### ISSUE TITLE
New compile error on Ubuntu 17.10 x64

### ISSUE THREAD

**Issue by GottfriedHofmann** [sebbas/blender-mantaflow#23]
[ 52%] Building C object source/blender/blenkernel/CMakeFiles/bf_blenkernel.dir/intern/pointcache.c.o
/home/g/blender-git/blender/source/blender/blenkernel/intern/pointcache.c: In function ‘BKE_ptcache_id_from_smoke’:
/home/g/blender-git/blender/source/blender/blenkernel/intern/pointcache.c:1743:28: error: ‘ptcache_mesh_write’ undeclared (first use in this function); did you mean ‘ptcache_smoke_write’?
   pid->write_mesh_stream = ptcache_mesh_write;
                            ^~~~~~~~~~~~~~~~~~
                            ptcache_smoke_write
/home/g/blender-git/blender/source/blender/blenkernel/intern/pointcache.c:1743:28: note: each undeclared identifier is reported only once for each function it appears in
/home/g/blender-git/blender/source/blender/blenkernel/intern/pointcache.c:1744:27: error: ‘ptcache_mesh_read’ undeclared (first use in this function); did you mean ‘ptcache_mesh_write’?
   pid->read_mesh_stream = ptcache_mesh_read;
                           ^~~~~~~~~~~~~~~~~
                           ptcache_mesh_write
source/blender/blenkernel/CMakeFiles/bf_blenkernel.dir/build.make:2438: recipe for target 'source/blender/blenkernel/CMakeFiles/bf_blenkernel.dir/intern/pointcache.c.o' failed
make[2]: *** [source/blender/blenkernel/CMakeFiles/bf_blenkernel.dir/intern/pointcache.c.o] Error 1
CMakeFiles/Makefile2:4540: recipe for target 'source/blender/blenkernel/CMakeFiles/bf_blenkernel.dir/all' failed
make[1]: *** [source/blender/blenkernel/CMakeFiles/bf_blenkernel.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

Notw: I am compiling without MOD_SMOKE and MOD_FLUID, just with MOD_MANTA

**Comment by sebbas** [comment]
For MOD_MANTA to work it is also necessary to enable MOD_SMOKE right now. But I see, it is probably time to merge those flags.

**Comment by GottfriedHofmann** [comment]
Oh, thanks for the info. With MOD_SMOKE enabled it compiles further but breaks eventually:

[ 53%] Building C object source/blender/blenkernel/CMakeFiles/bf_blenkernel.dir/intern/smoke.c.o
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c: In function ‘smoke_reallocate_highres_fluid’:
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:151:89: warning: unused parameter ‘free_old’ [-Wunused-parameter]
 void smoke_reallocate_highres_fluid(SmokeDomainSettings *sds, float dx, int res[3], int free_old)
                                                                                         ^~~~~~~~
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c: In function ‘smokeModifier_createType’:
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:573:31: error: incompatible type for argument 2 of ‘BLI_make_file_string’
    BLI_make_file_string("/",  BLI_path_make_safe(smd->domain->cache_directory), BKE_tempdir_base(), "");
                               ^~~~~~~~~~~~~~~~~~
In file included from /home/g/blender-git/blender/source/blender/blenlib/BLI_blenlib.h:74:0,
                 from /home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:43:
/home/g/blender-git/blender/source/blender/blenlib/BLI_path_util.h:45:6: note: expected ‘char *’ but argument is of type ‘_Bool’
 void BLI_make_file_string(const char *relabase, char *string,  const char *dir, const char *file);
      ^~~~~~~~~~~~~~~~~~~~
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c: In function ‘update_flowsfluids’:
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:2685:29: warning: variable ‘index_big’ set but not used [-Wunused-but-set-variable]
    size_t e_index, d_index, index_big;
                             ^~~~~~~~~
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:2682:11: warning: unused variable ‘distance_map_high’ [-Wunused-variable]
    float* distance_map_high = em->distances_high;
           ^~~~~~~~~~~~~~~~~
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:2662:9: warning: unused variable ‘bigcolor_b’ [-Wunused-variable]
  float *bigcolor_b = smoke_turbulence_get_color_b(sds->fluid);
         ^~~~~~~~~~
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:2661:9: warning: unused variable ‘bigcolor_g’ [-Wunused-variable]
  float *bigcolor_g = smoke_turbulence_get_color_g(sds->fluid);
         ^~~~~~~~~~
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:2660:9: warning: unused variable ‘bigcolor_r’ [-Wunused-variable]
  float *bigcolor_r = smoke_turbulence_get_color_r(sds->fluid);
         ^~~~~~~~~~
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:2659:9: warning: unused variable ‘bigreact’ [-Wunused-variable]
  float *bigreact = smoke_turbulence_get_react(sds->fluid);
         ^~~~~~~~
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:2658:9: warning: unused variable ‘bigfuel’ [-Wunused-variable]
  float *bigfuel = smoke_turbulence_get_fuel(sds->fluid);
         ^~~~~~~
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:2656:7: warning: unused variable ‘num_flowobj’ [-Wunused-variable]
  int *num_flowobj = fluid_get_num_flow(sds->fluid);
       ^~~~~~~~~~~
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:2655:7: warning: unused variable ‘flow_type’ [-Wunused-variable]
  int *flow_type = fluid_get_flow_type(sds->fluid);
       ^~~~~~~~~
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:2646:9: warning: unused variable ‘velz_initial’ [-Wunused-variable]
  float *velz_initial = smoke_get_in_velocity_z(sds->fluid);
         ^~~~~~~~~~~~
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:2645:9: warning: unused variable ‘vely_initial’ [-Wunused-variable]
  float *vely_initial = smoke_get_in_velocity_y(sds->fluid);
         ^~~~~~~~~~~~
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:2644:9: warning: unused variable ‘velx_initial’ [-Wunused-variable]
  float *velx_initial = smoke_get_in_velocity_x(sds->fluid);
         ^~~~~~~~~~~~
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c: In function ‘smoke_init_geometry’:
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:2942:8: warning: variable ‘dtSubdiv’ set but not used [-Wunused-but-set-variable]
  float dtSubdiv;
        ^~~~~~~~
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:2941:6: warning: unused variable ‘substep’ [-Wunused-variable]
  int substep = 0;
      ^~~~~~~
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c: In function ‘smoke_make_geometry’:
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:3445:15: warning: unused variable ‘dm’ [-Wunused-variable]
  DerivedMesh *dm = ob->derivedDeform;
               ^~
At top level:
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:2935:13: warning: ‘smoke_init_geometry’ defined but not used [-Wunused-function]
 static void smoke_init_geometry(Scene *scene, Object *ob, SmokeModifierData *smd, DerivedMesh *domain_dm, float fps)
             ^~~~~~~~~~~~~~~~~~~
/home/g/blender-git/blender/source/blender/blenkernel/intern/smoke.c:1139:13: warning: ‘subframe_updateObject’ defined but not used [-Wunused-function]
 static bool subframe_updateObject(Scene *scene, Object *ob, int update_mesh, int parent_recursion, float frame, bool for_render)
             ^~~~~~~~~~~~~~~~~~~~~
source/blender/blenkernel/CMakeFiles/bf_blenkernel.dir/build.make:2750: recipe for target 'source/blender/blenkernel/CMakeFiles/bf_blenkernel.dir/intern/smoke.c.o' failed
make[2]: *** [source/blender/blenkernel/CMakeFiles/bf_blenkernel.dir/intern/smoke.c.o] Error 1
CMakeFiles/Makefile2:4561: recipe for target 'source/blender/blenkernel/CMakeFiles/bf_blenkernel.dir/all' failed
make[1]: *** [source/blender/blenkernel/CMakeFiles/bf_blenkernel.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sebbas** [comment]
You're right, I just tried it out and it also failed on my Linux. So I did some cleanup among the warnings and also combined the "WITH_SMOKE" and "WITH_MANTA" macros. Now there is only "WITH_MANTA".

Think it should be fixed starting from 77e3cacc798474df83285d0b93393c1f9d2b2269. Thanks for pointing this out!

**Comment by GottfriedHofmann** [comment]
Thank you, it compiles again (even thouth the new bake system appears to be in a kinda unusable state right now :(
