### ISSUE TITLE
Baking but no result

### ISSUE THREAD

**Issue by GottfriedHofmann** [sebbas/blender-mantaflow#3]
Hello Sebbas,

I just tried the latest Mantaflow build by Jens Verwiebe (https://blenderartists.org/forum/showthread.php?373547-Lets-talk-about-Mantaflow&p=3164514&viewfull=1#post3164514) and created a very simple scene. When i hit "bake", the baking process starts. Once it is finished, nothing has changed in the viewport. 

Here is the file for you to test: http://pasteall.org/blend/index.php?id=45939

**Comment by sebbas** [comment]
Hi Gottfried,

it's just some things that are probably not so intuitive right now:
- In the "Fluid Cache" panel, change the file form from "Point cache" to "Object files"
- Set the border collisions in the domain to "Collide All" (optional, but I think it makes more sense)

Other than that, the splash from the scene is probably not so realistic. I am still working on external object velocities for liquids - it just requires slightly more accuracy than when smoke is hit by an object.

The adapted scene is over here: http://pasteall.org/blend/index.php?id=45941

**Comment by GottfriedHofmann** [comment]
Thanks for the explanation. In case of liquids, only "object" makes sense as cache I guess so you could set it automatically and hide the drop-down?

Btw: The height of the fluid does not change when the cube falls into it. It seems like it just gets deleted from where the cube is but there is no expulsion (es wird kein Wasser verdrängt, der Wasserstand im Tank steigt nicht an).

**Comment by sebbas** [comment]
Oh yeah, I know what you mean. In fact, the obstacle **is** currently only "deleting" instead of "pushing and only then deleting" remaining liquid (FLIP particles) inside the collision object.

Consider it a dirty "placeholder" :) (..until I have setup the obstacle velocities for liquids).

**Comment by sebbas** [comment]
@GottfriedHofmann Latest commit (Hash 137c035) sets all the settings automatically :)
