### ISSUE TITLE
how to launch?

### ISSUE THREAD

**Issue by matyklug18** [sebbas/blender-mantaflow#30]
i downloaded the zip, but how should i launch it? ./blender gives me error:  error while loading shared libraries: libOpenImageIO.so.1.8: cannot open shared object file: No such file or directory

**Comment by juangea** [comment]
What do you mean? 
Right now it’s a Blender branch, when you compile it you get a Blender compilation, you launch that version and it has Mantaflow integrated

**Comment by matyklug18** [comment]
i downloaded the zip from releases. it isnt compiled already? or could you please provide build instructions?

**Comment by juangea** [comment]
Yes it is, when you unzip it you will get a blender version, run it and this Blender already have Mantaflow

**Comment by matyklug18** [comment]
so i run file "blender"? i also forgot to say that i am on linux. if i run it, it gives me error: ./blender: error while loading shared libraries: libOpenImageIO.so.1.8: cannot open shared object file: No such file or directory

**Comment by juangea** [comment]
Maybe the Linux build is not made with static libraries, so you may have to install the libraries, or maybe Sebas can make a static version, I’m not sure how to compile a static version on Linux

**Comment by matyklug18** [comment]
i dont know how to install the lib, as it isnt anywhere to be found. i searched in app store, package repos, google, just nothing. only not compiled version with no compile instructions and outdated version in app store.

**Comment by juangea** [comment]
If you go to the “how to build Blender” page in the wiki you will see there are instructions to download and install all the required libs for building Blender, I’m on the phone so I cannot give you the exact link, but if you search “build blender” on google you will find it :)

**Comment by matyklug18** [comment]
So i downloaded the dependencies script, installed one lib and it works! I think you should ship the script with the release.

**Comment by juangea** [comment]
Nah, the problem is that the build is not made with static dependencies, it should be made that way, but it’s a bit of a mess to build with static libs (at least for me hahaha)

Cheers!
