### ISSUE TITLE
Liquid Sim | When resolution >64 Blender crashes after finishing simulation

### ISSUE THREAD

**Issue by michal1000w** [sebbas/blender-mantaflow#34]
I've tried it on few blender projects and in every one after I've set resolution of the domain to any value greater than 64 blender crashes every time after finishing the simulation. I've tried also canceling it before the end and sometimes it does not crash but most of the time it would.

I've tried few versions of Mantaflow also the latest but the problem still appears.

OS: Windows 10; CPU: Threadripper 2950X; GPU: RTX 2080; RAM: 64GB

**Comment by michal1000w** [comment]
The error is: 
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF6A9C5B262

**Comment by michal1000w** [comment]
Update: In the latest build it also works most of the time with resolution of 96

**Comment by sebbas** [comment]
Hi!

thanks for pointing this out, can you attach the blend file so that I can try to reproduce the issue?

**Comment by michal1000w** [comment]
This is the file:
[ship big.zip](https://github.com/sebbas/BlenderMantaflow/files/3703049/ship.big.zip)
Thanks for your time :D

**Comment by sebbas** [comment]
Thanks for the file! So far there are no crashes, but I will try more.

Can you also try enabling "Use Adaptive Stepping" in the domain options? It would be interesting to see if you get the same crashes with that enabled.

**Comment by michal1000w** [comment]
I've tried it again few times and with resolution of 200 it crashes also during the simulation (not only at the end).
And I've tried it both with adaptive stepping enabled and disabled so it's probably not the problem.
Maybe it's more hardware related so I'll try to do it also on my old i5 computer with just 4 threads cuz maybe there is a problem with 32

**Comment by sebbas** [comment]
Ok, I got my first crash, also when I tried simulating at resolution 200. It's definitely not your hardware, just some fine-tuning that's needed.

Can you try again with the latest commit? I changed some things that I think might have caused the crash.

**Comment by michal1000w** [comment]
I've just compiled it and it didn't crash at resolution 200 and additional particles also stared working :D
Thank's a lot and have a nice evening
