### ISSUE TITLE
NO RENDER “DEMO FILES - Physics - Fluid simulation file - APIC vs FLIP solver”

### ISSUE THREAD

**Issue by GLuke67** [sebbas/blender-mantaflow#39]
Why IS NOT POSSIBLE render any images (F12) of frames of the file "Fluid simulation file - APIC vs FLIP solver.blend", after the Bake All ?

The demo file I used is Fluid simulation file - APIC vs FLIP solver.blend and you can download at https://www.blender.org/download/demo-files/

https://download.blender.org/demo/physics/fluid-simulation_flip_vs_apic_solver.blend

**Comment by sebbas** [comment]
Hi! There was in fact an issue with that file. Can you download the file again and see if it works now?

**Comment by GLuke67** [comment]
Hi! now this file is perfect and it works!! I’m grateful for your assistance. Thanks so much!

**Comment by sebbas** [comment]
Glad it works!
