### ISSUE TITLE
Is this branch stable enough for compiling and testing?

### ISSUE THREAD

**Issue by mbakkokom** [sebbas/blender-mantaflow#4]
Hello.

I'm just wondering if I can get a _stable_ snapshot of the code. I've tried multiple times in the past to compile it but it always failed.
The last time, it was caused by the Python code inside the custom build.

Thanks.

**Comment by sebbas** [comment]
Hi! 

you should be able to build the branch without any compilation problems. As for testing the actual build, there might be some glitches as it's still under development.

Without digging any deeper, did you compile with C++11 support? That's a requirement and common issue.
This should work (confirmed for hash 6f67dc1): 

`cmake ../blender -DWITH_CXX11=ON`

Cheers, Sebastián

**Comment by sebbas** [comment]
Closing this now. Over on the Blender Wiki, I set up a page with building instructions that I'll keep up-to-date. Just in case.

https://wiki.blender.org/index.php/User:Sebbas/Blender_Mantaflow/Building
