### ISSUE TITLE
Smoke size via particle size

### ISSUE THREAD

**Issue by Gerkinfeltser** [sebbas/blender-mantaflow#5]
Thank you so much for all your hard work! This is really a great addition to Blender & I look forward to the day it will be in the official builds.

Would it be possible for particle-emitted smoke/flames to inherit sizes from their parent particle? Currently, all smoke/flame emitted via particles use a uniform value for their size. Thank you again!

**Comment by sebbas** [comment]
Thanks for the encouraging words! 

Yes, I see this is certainly a bit of a shortcoming in the current implementation. For now, I put it on my To-Do list. I can take a closer a look once I am done with my current project on particles and fluid guiding.

**Comment by Gerkinfeltser** [comment]
Excellent! Thanks so much & keep up the amazing work!
